"""empty message

Revision ID: 15cde5450063
Revises: 19f4c787748b
Create Date: 2020-05-09 09:48:57.315170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cde5450063'
down_revision = '19f4c787748b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('currency', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'currency')
    # ### end Alembic commands ###
