"""empty message

Revision ID: 6bdfd5234ac6
Revises: 
Create Date: 2020-04-25 14:39:26.068427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdfd5234ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('likes', sa.INTEGER(), nullable=False),
    sa.Column('dislikes', sa.INTEGER(), nullable=False),
    sa.Column('post', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
