"""empty message

Revision ID: 19f4c787748b
Revises: b87a899f9bea
Create Date: 2020-05-09 09:47:34.631083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f4c787748b'
down_revision = 'b87a899f9bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('currency', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'currency')
    # ### end Alembic commands ###
