"""empty message

Revision ID: b87a899f9bea
Revises: 2d11a943e103
Create Date: 2020-05-09 09:46:22.306714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87a899f9bea'
down_revision = '2d11a943e103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('currency', sa.Text(), nullable=False))
    op.alter_column('positions', 'percent',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'percent',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('positions', 'currency')
    # ### end Alembic commands ###
